INSERT INTO `comuna` (`id`,`nombre`)
VALUES

	(1,'Colina'),
	(2,'Lampa'),
	(3,'Tiltil'),
	(4,'Santiago'),
	(5,'Vitacura'),
  	(6,'San Ramón'),
	(7,'San Miguel'),
	(8,'San Joaquín'),
  	(9,'Renca'),
	(10,'Recoleta'),
  	(11,'Quinta Normal'),
	(12,'Quilicura'),
  	(13,'Pudahuel'),
  	(14,'Providencia'),
	(15,'Peñalolén'),
  	(16,'Pedro Aguirre Cerda'),
	(17,'Ñuñoa'),
	(18,'Maipú'),
	(19,'Macul'),
	(20,'Lo Prado'),
	(21,'Lo Espejo'),
	(22,'Lo Barnechea'),
	(23,'Las Condes'),
	(24,'La Reina'),
	(25,'La Pintana'),
	(26,'La Granja'),
	(27,'La Florida'),
  	(28,'La Cisterna'),
  	(29,'Independencia'),
  	(30,'Huechuraba'),
	(31,'Estación Central'),
  	(32,'El Bosque'),
  	(33,'Conchalí'),
  	(34,'Cerro Navia'),
  	(35,'Cerrillos'),
	(36,'Puente Alto'),
	(37,'San José de Maipo'),
  	(38,'Pirque'),
	(39,'San Bernardo'),
	(40,'Buin'),
  	(41,'Paine'),
	(42,'Calera de Tango'),
	(43,'Melipilla'),
	(44,'Alhué'),
	(45,'Curacaví'),
	(46,'María Pinto'),
	(47,'San Pedro'),
	(48,'Isla de Maipo'),
  	(49,'El Monte'),
	(50,'Padre Hurtado'),
	(51,'Peñaflor'),
	(52,'Talagante');
