"""empty message

Revision ID: 33ad617127c9
Revises: 
Create Date: 2022-05-18 02:25:25.107609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33ad617127c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('foto_perfil', sa.String(length=120), nullable=True),
    sa.Column('biografia', sa.String(length=500), nullable=True),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comuna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oferta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('area', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('carrera_requerida', sa.String(length=120), nullable=False),
    sa.Column('fecha_inicio', sa.String(length=120), nullable=False),
    sa.Column('fecha_termino', sa.String(length=120), nullable=False),
    sa.Column('comuna_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comuna_id'], ['comuna.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practicante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(length=120), nullable=False),
    sa.Column('institucion', sa.String(length=120), nullable=False),
    sa.Column('foto_perfil', sa.String(length=120), nullable=True),
    sa.Column('biografia', sa.String(length=500), nullable=True),
    sa.Column('carrera_estudio', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('anexo1', sa.String(length=120), nullable=True),
    sa.Column('anexo2', sa.String(length=120), nullable=True),
    sa.Column('comuna_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comuna_id'], ['comuna.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('postulacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_postulacion', sa.String(length=120), nullable=False),
    sa.Column('practicante_id', sa.Integer(), nullable=True),
    sa.Column('oferta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['oferta_id'], ['oferta.id'], ),
    sa.ForeignKeyConstraint(['practicante_id'], ['practicante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postulacion')
    op.drop_table('practicante')
    op.drop_table('oferta')
    op.drop_table('comuna')
    op.drop_table('region')
    op.drop_table('empresa')
    op.drop_table('administrador')
    # ### end Alembic commands ###
